"""Add icon_image field to skills table

Revision ID: 151641f0bba8
Revises: b57e3f52a873
Create Date: 2025-12-26 11:04:22.185451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151641f0bba8'
down_revision = 'b57e3f52a873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_image', sa.String(length=500), nullable=True))
        batch_op.alter_column('icon_text',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('icon_text',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_column('icon_image')

    # ### end Alembic commands ###
