"""Add google_drive_link to projects

Revision ID: 194e474b5504
Revises: 4d324a25eaa8
Create Date: 2025-12-25 21:55:36.945971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194e474b5504'
down_revision = '4d324a25eaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_drive_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('google_drive_link')

    # ### end Alembic commands ###
