"""Add ServiceCategory and update Service

Revision ID: 20d509b55559
Revises: 5fa0a4cfa54e
Create Date: 2025-12-22 22:06:35.877489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d509b55559'
down_revision = '5fa0a4cfa54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_services_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_services_category_id_service_categories', 'service_categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_services_category_id_service_categories', type_='foreignkey')
        batch_op.drop_constraint('fk_services_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('image_url')

    op.drop_table('service_categories')
    # ### end Alembic commands ###
