"""Add ProjectCategory and category_id to projects

Revision ID: 4d324a25eaa8
Revises: 6e2669ffbf87
Create Date: 2025-12-25 21:40:16.333345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d324a25eaa8'
down_revision = '6e2669ffbf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_project_categories_name'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_category_id_project_categories'), 'project_categories', ['category_id'], ['id'])
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('price')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_projects_category_id_project_categories'), type_='foreignkey')
        batch_op.drop_column('image_url')
        batch_op.drop_column('category_id')

    op.drop_table('project_categories')
    # ### end Alembic commands ###
