"""Add new dynamic fields to AboutContent

Revision ID: 5952f6e8a588
Revises: ea9c0143f5d5
Create Date: 2025-12-31 13:13:18.736660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5952f6e8a588'
down_revision = 'ea9c0143f5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_skills')
    # with op.batch_alter_table('about_content', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('hero_stat_1_count', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('hero_stat_1_label', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('hero_stat_2_count', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('hero_stat_2_label', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('hero_stat_3_count', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('hero_stat_3_label', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('hero_image_url', sa.String(length=255), nullable=True))
    #     batch_op.add_column(sa.Column('value4_title', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('value4_description', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('value5_title', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('value5_description', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('value6_title', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('value6_description', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_year_1', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_title_1', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_content_1', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_year_2', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_title_2', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_content_2', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_year_3', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_title_3', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_content_3', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_year_4', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_title_4', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('timeline_content_4', sa.Text(), nullable=True))
    #     batch_op.add_column(sa.Column('cta_button_2_text', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('cta_button_link', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('cta_button_2_link', sa.String(length=100), nullable=True))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('icon_text',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('icon_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_image', sa.VARCHAR(length=500), nullable=True))
        batch_op.alter_column('icon_text',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('about_content', schema=None) as batch_op:
        batch_op.drop_column('cta_button_2_link')
        batch_op.drop_column('cta_button_link')
        batch_op.drop_column('cta_button_2_text')
        batch_op.drop_column('timeline_content_4')
        batch_op.drop_column('timeline_title_4')
        batch_op.drop_column('timeline_year_4')
        batch_op.drop_column('timeline_content_3')
        batch_op.drop_column('timeline_title_3')
        batch_op.drop_column('timeline_year_3')
        batch_op.drop_column('timeline_content_2')
        batch_op.drop_column('timeline_title_2')
        batch_op.drop_column('timeline_year_2')
        batch_op.drop_column('timeline_content_1')
        batch_op.drop_column('timeline_title_1')
        batch_op.drop_column('timeline_year_1')
        batch_op.drop_column('value6_description')
        batch_op.drop_column('value6_title')
        batch_op.drop_column('value5_description')
        batch_op.drop_column('value5_title')
        batch_op.drop_column('value4_description')
        batch_op.drop_column('value4_title')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('hero_stat_3_label')
        batch_op.drop_column('hero_stat_3_count')
        batch_op.drop_column('hero_stat_2_label')
        batch_op.drop_column('hero_stat_2_count')
        batch_op.drop_column('hero_stat_1_label')
        batch_op.drop_column('hero_stat_1_count')

    op.create_table('_alembic_tmp_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('percentage', sa.INTEGER(), nullable=False),
    sa.Column('icon_text', sa.VARCHAR(length=10), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    # ### end Alembic commands ###
