"""Add AboutContent model

Revision ID: 6e2669ffbf87
Revises: c00c0d49346d
Create Date: 2025-12-22 23:47:57.042120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2669ffbf87'
down_revision = 'c00c0d49346d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_content',
    sa.Column('hero_title', sa.String(length=200), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('mission_title', sa.String(length=100), nullable=False),
    sa.Column('mission_content', sa.Text(), nullable=False),
    sa.Column('vision_title', sa.String(length=100), nullable=False),
    sa.Column('vision_content', sa.Text(), nullable=False),
    sa.Column('values_title', sa.String(length=100), nullable=False),
    sa.Column('value1_title', sa.String(length=100), nullable=False),
    sa.Column('value1_description', sa.Text(), nullable=False),
    sa.Column('value2_title', sa.String(length=100), nullable=False),
    sa.Column('value2_description', sa.Text(), nullable=False),
    sa.Column('value3_title', sa.String(length=100), nullable=False),
    sa.Column('value3_description', sa.Text(), nullable=False),
    sa.Column('story_title', sa.String(length=100), nullable=False),
    sa.Column('story_content', sa.Text(), nullable=False),
    sa.Column('team_title', sa.String(length=100), nullable=False),
    sa.Column('team_subtitle', sa.Text(), nullable=False),
    sa.Column('cta_title', sa.String(length=100), nullable=False),
    sa.Column('cta_subtitle', sa.Text(), nullable=False),
    sa.Column('cta_button_text', sa.String(length=50), nullable=False),
    sa.Column('singleton_guard', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about_content')),
    sa.UniqueConstraint('singleton_guard', name=op.f('uq_about_content_singleton_guard'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_content')
    # ### end Alembic commands ###
