"""Add blog posts table

Revision ID: 6f95bf866aa0
Revises: f942598eb413
Create Date: 2025-12-31 11:10:38.897660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f95bf866aa0'
down_revision = 'f942598eb413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('read_time', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    # op.drop_table('_alembic_tmp_skills')
    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.alter_column('icon_text',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=False)
    #     batch_op.drop_column('icon_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('icon_image', sa.VARCHAR(length=500), nullable=True))
    #     batch_op.alter_column('icon_text',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=True)

    # op.create_table('_alembic_tmp_skills',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('percentage', sa.INTEGER(), nullable=False),
    # sa.Column('icon_text', sa.VARCHAR(length=10), nullable=False),
    # sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    # sa.Column('order', sa.INTEGER(), nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    # )
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
