"""Add YouTubeCategory model

Revision ID: 70c8bde30da9
Revises: 151641f0bba8
Create Date: 2025-12-30 23:43:00.979407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c8bde30da9'
down_revision = '151641f0bba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_youtube_categories_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_categories')
    # ### end Alembic commands ###
