"""Add HomeContent model

Revision ID: c00c0d49346d
Revises: 20d509b55559
Create Date: 2025-12-22 23:43:56.054970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00c0d49346d'
down_revision = '20d509b55559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_content',
    sa.Column('hero_title_line1', sa.String(length=100), nullable=False),
    sa.Column('hero_title_line2', sa.String(length=100), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('profile_image', sa.String(length=300), nullable=True),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('profile_title', sa.String(length=100), nullable=False),
    sa.Column('profile_rating', sa.String(length=10), nullable=False),
    sa.Column('profile_skills', sa.String(length=500), nullable=False),
    sa.Column('stat_projects', sa.String(length=20), nullable=False),
    sa.Column('stat_materials', sa.String(length=20), nullable=False),
    sa.Column('stat_team', sa.String(length=20), nullable=False),
    sa.Column('stat_downloads', sa.String(length=20), nullable=False),
    sa.Column('knowledge_hub_title', sa.String(length=100), nullable=False),
    sa.Column('knowledge_hub_subtitle', sa.Text(), nullable=False),
    sa.Column('workflow_title', sa.String(length=100), nullable=False),
    sa.Column('workflow_subtitle', sa.Text(), nullable=False),
    sa.Column('cv_button_text', sa.String(length=50), nullable=False),
    sa.Column('cv_button_link', sa.String(length=300), nullable=True),
    sa.Column('hire_button_text', sa.String(length=50), nullable=False),
    sa.Column('singleton_guard', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_home_content')),
    sa.UniqueConstraint('singleton_guard', name=op.f('uq_home_content_singleton_guard'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    op.drop_table('home_content')
    # ### end Alembic commands ###
