"""Add home page dynamic content models

Revision ID: e1278bf90a4d
Revises: 62d3604cca08
Create Date: 2025-12-25 22:57:26.434454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1278bf90a4d'
down_revision = '62d3604cca08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title_line1', sa.String(length=200), nullable=False),
    sa.Column('hero_title_line2', sa.String(length=200), nullable=False),
    sa.Column('hero_subtitle', sa.Text(), nullable=False),
    sa.Column('cv_button_text', sa.String(length=100), nullable=True),
    sa.Column('cv_button_link', sa.String(length=500), nullable=True),
    sa.Column('hire_button_text', sa.String(length=100), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('stat1_value', sa.String(length=20), nullable=True),
    sa.Column('stat1_label', sa.String(length=100), nullable=True),
    sa.Column('stat2_value', sa.String(length=20), nullable=True),
    sa.Column('stat2_label', sa.String(length=100), nullable=True),
    sa.Column('stat3_value', sa.String(length=20), nullable=True),
    sa.Column('stat3_label', sa.String(length=100), nullable=True),
    sa.Column('stat4_value', sa.String(length=20), nullable=True),
    sa.Column('stat4_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_home_page_content'))
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('icon_text', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('dribbble_url', sa.String(length=500), nullable=True),
    sa.Column('behance_url', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('skills')
    op.drop_table('home_page_content')
    # ### end Alembic commands ###
