"""Add blog categories

Revision ID: ea9c0143f5d5
Revises: 6f95bf866aa0
Create Date: 2025-12-31 11:15:12.877769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9c0143f5d5'
down_revision = '6f95bf866aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_blog_categories_name'))
    )
    # op.drop_table('_alembic_tmp_skills')
    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.alter_column('icon_text',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=False)
    #     batch_op.drop_column('icon_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('icon_image', sa.VARCHAR(length=500), nullable=True))
    #     batch_op.alter_column('icon_text',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=True)

    # op.create_table('_alembic_tmp_skills',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    # sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('percentage', sa.INTEGER(), nullable=False),
    # sa.Column('icon_text', sa.VARCHAR(length=10), nullable=False),
    # sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    # sa.Column('order', sa.INTEGER(), nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    # )
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
