"""Add doc_url field to StudyMaterial

Revision ID: f942598eb413
Revises: 70c8bde30da9
Create Date: 2025-12-31 10:27:02.621059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f942598eb413'
down_revision = '70c8bde30da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('doc_url')

    # ### end Alembic commands ###
